name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [14.0x, 16.x, 18.x]
        os: [macos-latest, ubuntu-latest]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Setup Node ${{ matrix.node_version }}
        uses: actions/setup-node@v1
      - name: Install
        run: yarn install --ignore-engines
      - name: build
        run: yarn build
      - name: test
        run: yarn test
